Dominio/WebObligatorio/ViewModels/AltaProyectoCooperativo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace WebObligatorio.ViewModels
{
    public class AltaProyectoCooperativo
    {
        [Display(Name = "Titulo")]
        [Required(ErrorMessage = "El titulo es requerido")]
        public string titulo { get; set; }

        [Display(Name = "Descripcion")]
        [Required(ErrorMessage = "debe ingresar una descripcion")]
        public string descripcion { get; set; }

        [Display(Name = "Monto a Solicitar")]
        [Required(ErrorMessage = "Ingrese un monto 3")]
        public decimal montoSolicitado { get; set; }

        [Display(Name = "Cantidad de Cuotas")]
        [Required(ErrorMessage = "MontoSolicitado")]
        [Range(1, 16)]
        public int cantidadCuotas { get; set; }


        public HttpPostedFileBase Archivo { get; set; }


        [Display(Name = "Cantidad Integrantes")]
        [Required(ErrorMessage = "Ingrese cantidad de integrantes")]
        public int cantIntegrantes { get; set; }



    }
}

Dominio/WebObligatorio/ViewModels/AltaProyectoPersonal.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace WebObligatorio.ViewModels
{
    public class AltaProyectoPersonal
    {
        [Display(Name = "Titulo")]
        [Required(ErrorMessage = "El titulo es requerido")]
        public string titulo { get; set; }

        [Display(Name = "Descripcion")]
        [Required(ErrorMessage = "debe ingresar una descripcion")]
        public string descripcion { get; set; }

        [Display(Name = "Monto a Solicitar")]
        [Required(ErrorMessage = "Ingrese un monto 3")]
        public decimal montoSolicitado { get; set; }

        [Display(Name = "Cantidad de Cuotas")]
        [Required(ErrorMessage = "MontoSolicitado")]
        [Range(1, 16)]
        public int cantidadCuotas { get; set; }


        public HttpPostedFileBase Archivo { get; set; }



        ////Cooperativo 
        //[Display(Name = "Cantidad Integrantes")]
        //[Required(ErrorMessage = "Ingrese cantidad de integrantes")]
        //public int cantIntegrantes { get; set; }

        //Personal
        [Display(Name = "Descripcion Personal ")]
        [Required(ErrorMessage = "Ingrese una descripcion personal")]
        public string descripcionPersonal { get; set; }
    }
}

Dominio/WebObligatorio/ViewModels/EvaluacionProyectoViewModel.cs
using Dominio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebObligatorio.ViewModels
{
    public class EvaluacionProyectoViewModel
    {
        public Proyecto Proyecto { get; set; }
        public int Puntaje { get; set; }
    }
}

Dominio/WebObligatorio/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Repositorios;
using Dominio;
using System.IO;
using WebObligatorio.ViewModels;
using System.Configuration;

namespace WebObligatorio.Controllers
{
    public class UsuarioController : Controller
    {
        [HttpGet]
        public ActionResult Index(string mensaje)
        {
            if (Session["cedula"] != null)
            {
                return Redirect("/Usuario/Loguear");
            }
            else
            {
                ViewBag.Mensaje2 = mensaje;
                return View();
            }
        }

        [HttpPost]
        public ActionResult Index(int cedula, string pass)
        {
            if (cedula > 0 && pass.Length != 0)
            {
                bool validarCedulaEntre7y8Caracteres = Dominio.Usuario.ValidarCedula(cedula);
                if (validarCedulaEntre7y8Caracteres)
                {
                    Usuario usuario = FachadaPrestamos.buscarUsuarioPorCedula(cedula);
                    if (usuario != null)
                    {
                        if (usuario.Pass == pass)
                        {
                            Session["cedula"] = usuario.Cedula;
                            Session["tipo"] = usuario.Tipo;
                            Session["id"] = usuario.Id;
                           
                            return Redirect("/Usuario/Loguear");
                        }
                        else
                        {
                            ViewBag.mensaje = "La contraseña es incorrecta";
                        }
                    }
                    else
                    {
                        ViewBag.mensaje = "No hay usuario con esa cedula.";
                    }
                }
                else
                {
                    ViewBag.mensaje = "Ingrese una cedula valida entre 7 y 8 caracteres (Sin espacios ni guiones).";
                }

            }
            else
            {
                ViewBag.mensaje = "Todos los campos son requeridos.";
            }

            return View();
        }

        public ActionResult Loguear()

        {

       
            ViewBag.Carpeta = ConfigurationManager.AppSettings["CarpetaImagenes"];
            if (Session["cedula"] == null)
            {
                return Redirect("/usuario/Index");
            }
            else
            {
                if ((string)Session["tipo"] == "Solicitante")
                {
                    int idCliente = (int)Session["id"];
                    List<Proyecto> proyectos = FachadaPrestamos.listaDeProyectosDeUnCliente(idCliente);
                    return View(proyectos);
                }
                else
                {

                    return Redirect("/usuario/ListadoPendientes");
                }

            }
        }

        //Aca agregue view model en lugar de un solicitante para poder validar que 
        //Contraseña y verificar contraseña sean iguales con validaciones desde viewmodel
        //Y separar las validaciones de campos de nuestro dominio
        [HttpGet]
        public ActionResult Alta()
        {
            //Solicitante nuevoSoli = new Solicitante();
            //return View(nuevoSoli);

            AltaSolicitanteViewModel vm = new AltaSolicitanteViewModel();
            return View(vm);
        }

        [HttpPost]
        public ActionResult Alta(AltaSolicitanteViewModel vm)
        {
            if (vm != null)
            {
                bool celularValido = Dominio.Solicitante.ValidarFormatoCelular(vm.Celular);
                bool mailValido = Dominio.Solicitante.ValidarFormatoEmail(vm.Email);
                bool passValido = Dominio.Solicitante.ValidarFormatoPassword(vm.Pass);
                bool pass2Valido = Dominio.Solicitante.ValidarFormatoPassword(vm.Pass2);
                bool edadMayorA21 = Dominio.Solicitante.EdadMayorA21(vm.FechaNac);
                bool contraYVerificarContraIguales = Dominio.Solicitante.ContraYVerificarContraSonIguales(vm.Pass, vm.Pass2);
                bool validarCedulaEntre7y8Caracteres = Dominio.Usuario.ValidarCedula(vm.Cedula);

                if (celularValido && mailValido && passValido && pass2Valido && edadMayorA21 && contraYVerificarContraIguales && validarCedulaEntre7y8Caracteres)//Hacer todas las validaciones
                {
                    RepoUsuarios repoUsuario = new RepoUsuarios();

                    List<Proyecto> listaVacia = new List<Proyecto>();

                    bool exito = FachadaPrestamos.AltaSolicitante(vm.Cedula, vm.Nombre, vm.Apellido, vm.FechaNac, vm.Celular, vm.Email, vm.Pass, "Solicitante", false, listaVacia);
                    //Hardcodeado el tipo de solicitante porque siempre va a ser soli, solicitudes pendientes se inicializa en false y lista de proyectos vacia
                    if (exito)
                    {
                        return RedirectToAction("Index", new { mensaje = "Alta exitosa." });
                    }
                    else
                    {
                        //Aca viene si en la base de datos habia un unique
                        ViewBag.mensaje = "Asegurese de que la cedula y/o el email no esten registrados en la aplicacion.";
                    }

                }
                else
                {
                    //Agrega un mensaje para cada validacion es especial
                    if (!celularValido)
                    {
                        ViewBag.mensaje = "Verifique que el celular tenga el siguiente formato 09X YYYYY siendo X un numero del 1 al 9 y la Y uno del 0 al 9 (el espacio en blanco es obligatorio).\n";
                    }
                    if (!mailValido)
                    {
                        ViewBag.mensaje += "Verifique que el formato del email sea el correcto, no olvide arroba ni punto.\n";
                    }
                    if (!passValido || !pass2Valido)
                    {
                        ViewBag.mensaje += "Verifique que la contraseña contenga al menos 1 letra mayuscula, 1 minuscula, 1 digito y que al menos tenga 6 caracteres de largo.\n";
                    }
                    if (!edadMayorA21)
                    {
                        ViewBag.mensaje += "Debe ser mayor de 21 años para registrarse.\n";
                    }
                    if (!contraYVerificarContraIguales)
                    {
                        ViewBag.mensaje += "Contraseña y verificar contraseña no coinciden.\n";
                    }
                    if (!validarCedulaEntre7y8Caracteres)
                    {
                        ViewBag.mensaje += "Ingrese una cedula valida debe tener entre 7 y 8 caracteres numericos.\n";
                    }
                }
                return View(vm);
            }
            else
            {
                return Redirect("/Usuario/Loguear");
            }

        }


        [HttpGet]
        public ActionResult ListadoPendientes()
        {
            //Puse esto aca para que nos muestre siempre los proyectos al ingresar a la pag y que el admin lo firte si quiere
            ViewBag.Carpeta = ConfigurationManager.AppSettings["CarpetaImagenes"];
            List<Proyecto> p = FachadaPrestamos.TraerTodosLosProyectos();
            return View(p);
        }
        [HttpPost]
        public ActionResult ListadoPendientes(int? cedula, DateTime? fecha, string estado, string texto)
        {
            int ci = 0;
            DateTime Fecha = DateTime.MinValue;
            if (cedula != null)
            {
                ci = (int)cedula;
            }

            if (fecha != null)
            {
                Fecha = (DateTime)fecha;
                

            }
            ViewBag.Carpeta = ConfigurationManager.AppSettings["CarpetaImagenes"];
            string Estado = estado;
            string Texto = texto;
            List<Proyecto> p = FachadaPrestamos.BuscarProyectosPorFiltro(ci, Fecha, Estado, Texto);

            return View(p);
        }

        public ActionResult CerrarSesion()
        {
            Session["tipo"] = null;
            Session["cedula"] = null;
            Session["id"] = null;
            return RedirectToAction("index");
        }

    }
}

Dominio/WebObligatorio/Views/Proyecto/AltaProyectoCooperativo.cshtml
@model WebObligatorio.ViewModels.AltaProyectoCooperativo

@{
    ViewBag.Title = "AltaProyectoCooperativo";

}

<h2>AltaProyectoCooperativo</h2>
@if (@ViewBag.mensaje != null)
{
    <div class="alert alert-danger" role="alert">
        <p>@ViewBag.mensaje</p>
    </div>
}
@using (Html.BeginForm("AltaProyectoCooperativo", "Proyecto", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>AltaProyectoCooperativo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.montoSolicitado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.montoSolicitado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.montoSolicitado, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Imagen</label>
            <div class="col-md-10">
                <input type="file" class="form-control" name="Archivo" id="Archivo" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cantidadCuotas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cantidadCuotas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cantidadCuotas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cantIntegrantes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cantIntegrantes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cantIntegrantes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver al inicio", "Index", "Usuario")
</div>

Dominio/WebObligatorio/Views/Proyecto/AltaProyectoPersonal.cshtml
@model WebObligatorio.ViewModels.AltaProyectoPersonal



<h2>AltaProyectoPersonal</h2>
@if (@ViewBag.mensaje != null)
{
    <div class="alert alert-danger" role="alert">
        <p>@ViewBag.mensaje</p>
    </div>
}
@using (Html.BeginForm("AltaProyectoPersonal", "Proyecto", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Alta Proyecto Personal</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.montoSolicitado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.montoSolicitado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.montoSolicitado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cantidadCuotas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cantidadCuotas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cantidadCuotas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Imagen</label>
            <div class="col-md-10">
                <input type="file" class="form-control" name="Archivo" id="Archivo" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descripcionPersonal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcionPersonal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcionPersonal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver al inicio", "Index", "Usuario")
</div>

Dominio/WebObligatorio/Views/Proyecto/ConfirmarAltaProyectoCooperativo.cshtml
@model Dominio.Cooperativo

@{
    ViewBag.Title = "ConfirmarAltaProyectoCooperativo";
}



<div class="alert alert-danger" role="alert">
    <p>@ViewBag.mensaje</p>
</div>
<div class="col-sm-12">
    <h4>Cooperativo</h4>
    <hr />
    <dl class="dl-horizontal">


        <dt>
            @Html.DisplayNameFor(model => model.titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.montoSolicitado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.montoSolicitado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cantidadCuotas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cantidadCuotas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.urlImagen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.urlImagen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tasaInteres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tasaInteres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.montoMaximo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.montoMaximo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fechaPresentacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaPresentacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.montoCuota)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.montoCuota)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.montoFinalConInte)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.montoFinalConInte)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tipo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cantIntegrantes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cantIntegrantes)
        </dd>

    </dl>
</div>
<img src="~/@ViewBag.Carpeta/@Model.urlImagen " width="600" />



<div class="row">
    <div class="div-falso-boton btn btn-primary">
        @Html.ActionLink("Enviar Proyecto", "EnvioAltaCooperativo", "Proyecto")
    </div>
    <div class="div-falso-boton btn btn-primary">
        @Html.ActionLink("Cancelar", "AltaProyectoCooperativo", "Proyecto")
    </div>
</div>

Dominio/WebObligatorio/Views/Proyecto/EvaluacionProyecto.cshtml
@model Dominio.Personal

@{
    ViewBag.Title = "EvaluacionProyecto";
}

    <div class="container">

        <h2 >Evaluacion Proyecto Personal</h2>

        <h4>Personal</h4>
        <hr />
        <dl class="dl-horizontal">

            <dt>
                @Html.DisplayNameFor(model => model.titulo)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.titulo)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.descripcion)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.descripcion)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.montoSolicitado)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.montoSolicitado)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.cantidadCuotas)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.cantidadCuotas)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.tasaInteres)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.tasaInteres)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.estado)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.estado)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.montoMaximo)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.montoMaximo)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.fechaPresentacion)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.fechaPresentacion)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.montoCuota)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.montoCuota)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.montoFinalConInte)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.montoFinalConInte)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.tipo)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.tipo)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.descripcionPersonal)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.descripcionPersonal)
            </dd>

        </dl>

        <img src="~/@ViewBag.Carpeta/@Model.urlImagen " width="600" />

        <div class="row">
            <div class="col-md-3 form-horizontal mb-5">
                <form action="/Proyecto/EvaluacionProyecto" method="post">
                    <br />
                    <input type="number" value="0" class="form-control" name="puntaje" placeholder="Puntaje">
                    <br />
                    <input type="hidden" value="@Model.id" name="idProyecto" />
                    <button class="btn btn-primary" type="submit">
                        Enviar evaluacion
                    </button>
                    </br>
                    </br>
                    <div class="div-falso-boton btn btn-primary">
                        @Html.ActionLink("Cancelar", "ListadoPendientes", "Usuario")
                    </div>
                </form>
            </div>
        </div>


    </div>

Dominio/WebObligatorio/Views/Proyecto/EvaluacionProyectoCooperativo.cshtml
@model Dominio.Cooperativo

@{
    ViewBag.Title = "EvaluacionProyectoCooperativo";
}

    <div class="container">

        <h2>Evaluacion Proyecto Cooperativo</h2>

        <h4>Cooperativo</h4>
        <hr />
        <dl class="dl-horizontal">

            <dt>
                @Html.DisplayNameFor(model => model.titulo)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.titulo)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.descripcion)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.descripcion)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.montoSolicitado)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.montoSolicitado)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.cantidadCuotas)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.cantidadCuotas)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.tasaInteres)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.tasaInteres)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.estado)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.estado)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.montoMaximo)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.montoMaximo)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.fechaPresentacion)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.fechaPresentacion)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.montoCuota)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.montoCuota)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.montoFinalConInte)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.montoFinalConInte)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.tipo)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.tipo)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.cantIntegrantes)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.cantIntegrantes)
            </dd>

        </dl>

        <img src="~/@ViewBag.Carpeta/@Model.urlImagen " width="600" />


        <div class="row">
            <div class="col-md-3 form-horizontal mb-5">
                <form action="/Proyecto/EvaluacionProyecto" method="post">
                    <br />
                    <input type="number" value="0" class="form-control" name="puntaje" placeholder="Puntaje">
                    <br />
                    <input type="hidden" value="@Model.id" name="idProyecto" />
                    <button class="btn btn-primary" type="submit">
                        Enviar evaluacion
                    </button>
                    </br>
                    </br>
                    <div class="div-falso-boton btn btn-primary">
                        @Html.ActionLink("Cancelar", "ListadoPendientes", "Usuario")
                    </div>
                </form>
            </div>
        </div>
    </div>

Dominio/WebObligatorio/Views/Proyecto/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Alta de proyectos</h2>
<p>Seleccione una de las siguientes opciones:</p>

<div class="div-falso-boton btn btn-primary">
    @Html.ActionLink("Dar de alta un proyecto personal", "AltaProyectoPersonal", "Proyecto")
</div>

<div class="div-falso-boton btn btn-primary">
    @Html.ActionLink("Dar de alta un proyecto cooperativo", "AltaProyectoCooperativo", "Proyecto")
</div>